### ISSUE TITLE
Access with Ingress without TLS configuration

### ISSUE THREAD

**Issue by cwchoe** [kinvolk/headlamp#132]
Hello,

I got an error and there was blank screen when i try to access the url that host name and path defined in the Ingress yaml.
But the url  of Service ip and nodeport is working fine and there is only problem when using Ingress. 

This is the message on Chrome developer mode.  (The url is : "http://test.mycompany.com/monitor/ " but i got this)

GET http://test.mycompany.com/static/css/2.e4d123f2.chunk.css net::ERR_ABORTED 404 (Not Found) 
----------------------------------
my Ingress yaml is as follows:  (I don't think it has its own problem because it works for other services)

```
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: headlamp
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: test.mycompany.com
    http:
      paths:
      - path: /monitor(/|$)(.*)
        backend:
          serviceName: headlamp
          servicePort: 80
```
---------------------------------------

Could you give me some help to use ingress to access headlamp?

Thanks.
