### ISSUE TITLE
Keycloak and Headlamp

### ISSUE THREAD

**Issue by ws-way** [kinvolk/headlamp#209]
Hello,

We are unable to get Headlamp working with Keycloak. Do you have an example on how to configure Keycloak/Headlamp?

Thanks.

**Comment by joaquimrocha** [comment]
Hi, what's the use-case you're trying to accomplish when you write "Headlamp working with Keycloak"?

**Comment by ws-way** [comment]
We are running in K8s and we have a Keycloak server up and running, however we are unable to get it working with Keycloak and the Headlamp example on the webpage. We do have this config:

```
kind: Service
apiVersion: v1
metadata:
  name: headlamp
  namespace: kube-system
spec:
  ports:
    - port: 4466
      targetPort: 4466
  selector:
    k8s-app: headlamp
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      containers:
      - name: headlamp
        image: quay.io/kinvolk/headlamp:latest
        args:
          - "-in-cluster"
          - "-plugins-dir=/headlamp/plugins"
          - "-oidc-client-id=kubernetes"
          - "-oidc-client-secret=2f887c20-85b0-43ea-9911-56a911a396b2"
          - "-oidc-idp-issuer-url=https://sso.mydomain.com/auth/realms/sso/protocol/openid-connect/token"
        ports:
        - containerPort: 4466
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 4466
          initialDelaySeconds: 30
          timeoutSeconds: 30
      nodeSelector:
        'beta.kubernetes.io/os': linux
```
We do think that the -oidc-idp-issuer-url is the wrong one, but we do not know which value should be entered here.
