### ISSUE TITLE
Create/apply not working

### ISSUE THREAD

**Issue by saiyam1814** [kinvolk/headlamp#609]
Deployed headlamp onto Civo Kubernetes which is based on K3s. 
able to open UI and navigate but on creating it gives an error. 

<img width="1269" alt="Screenshot 2022-07-20 at 2 05 45 PM" src="https://user-images.githubusercontent.com/8190114/179937111-49690b80-eb83-464e-a00f-81efa951f204.png">

I used the standard installation steps with ingress
```
kubectl -n kube-system create serviceaccount headlamp-admin                                                             

kubectl create clusterrolebinding headlamp-admin --serviceaccount=kube-system:headlamp-admin --clusterrole=cluster-admi
kubectl apply -f https://raw.githubusercontent.com/kinvolk/headlamp/main/kubernetes-headlamp.yaml

```
ingress
```
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: headlamp
    namespace: kube-system
  spec:
    tls:
    - secretName: headlamp
      hosts:
      - headlamp.3b490ef9-d33c-42b7-a4f5-cd54bdff7c7e.k8s.civo.com
    rules:
    - host: headlamp.3b490ef9-d33c-42b7-a4f5-cd54bdff7c7e.k8s.civo.com
      http:
        paths:
        - backend:
            service:
              name: headlamp
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
```

<img width="1391" alt="Screenshot 2022-07-20 at 2 07 29 PM" src="https://user-images.githubusercontent.com/8190114/179937223-26df81b0-d813-4c1d-b19e-22f75340fe06.png">

Anything I am missing?
